version: '3.8'

services:
  # Test Database
  test_db:
    image: postgres:15
    container_name: sentinel_test_db
    environment:
      POSTGRES_DB: sentinel_test_db
      POSTGRES_USER: sentinel_test
      POSTGRES_PASSWORD: sentinel_test_password
    ports:
      - "15432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel_test -d sentinel_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sentinel_test_network

  # Test Services (using testing configuration)
  test_auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: sentinel_test_auth_service
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18005:8000"
    depends_on:
      test_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  test_spec_service:
    build:
      context: .
      dockerfile: spec_service/Dockerfile
    container_name: sentinel_test_spec_service
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18001:8000"
    depends_on:
      test_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  test_orchestration_service:
    build:
      context: .
      dockerfile: orchestration_service/Dockerfile
    container_name: sentinel_test_orchestration_service
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18002:8000"
    depends_on:
      test_spec_service:
        condition: service_healthy
      test_data_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  test_execution_service:
    build:
      context: .
      dockerfile: execution_service/Dockerfile
    container_name: sentinel_test_execution_service
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18003:8000"
    depends_on:
      test_data_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  test_data_service:
    build:
      context: .
      dockerfile: data_service/Dockerfile
    container_name: sentinel_test_data_service
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18004:8000"
    depends_on:
      test_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  test_api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: sentinel_test_api_gateway
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    ports:
      - "18000:8000"
    depends_on:
      test_auth_service:
        condition: service_healthy
      test_spec_service:
        condition: service_healthy
      test_orchestration_service:
        condition: service_healthy
      test_execution_service:
        condition: service_healthy
      test_data_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sentinel_test_network

  # Backend Test Runner Service
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: sentinel_test_runner
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    volumes:
      - .:/app
      - test_reports:/app/test_reports
    depends_on:
      test_api_gateway:
        condition: service_healthy
    command: ["pytest", "-v", "--tb=short", "--cov=.", "--cov-report=html:/app/test_reports/htmlcov", "--cov-report=xml:/app/test_reports/coverage.xml"]
    networks:
      - sentinel_test_network

  # Frontend Test Runner Service
  frontend_test_runner:
    build:
      context: ../sentinel_frontend
      dockerfile: Dockerfile.test
    container_name: sentinel_frontend_test_runner
    environment:
      - NODE_ENV=test
      - CI=true
      - REACT_APP_API_URL=http://test_api_gateway:8000
    volumes:
      - ../sentinel_frontend:/app
      - frontend_test_reports:/app/coverage
    command: ["npm", "run", "test:coverage"]
    networks:
      - sentinel_test_network

  # E2E Test Runner Service
  e2e_test_runner:
    build:
      context: ../sentinel_frontend
      dockerfile: Dockerfile.e2e
    container_name: sentinel_e2e_test_runner
    environment:
      - NODE_ENV=test
      - CI=true
      - REACT_APP_API_URL=http://test_api_gateway:8000
      - PLAYWRIGHT_HEADLESS=true
    volumes:
      - ../sentinel_frontend:/app
      - e2e_test_reports:/app/test-results
    depends_on:
      test_api_gateway:
        condition: service_healthy
      frontend_test_runner:
        condition: service_completed_successfully
    command: ["npx", "playwright", "test", "--reporter=html"]
    networks:
      - sentinel_test_network

  # Test Data Loader Service (Optional - for loading test fixtures)
  test_data_loader:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: sentinel_test_data_loader
    environment:
      - SENTINEL_ENVIRONMENT=testing
    env_file:
      - config/testing.env
    volumes:
      - ./tests/fixtures:/app/fixtures
    depends_on:
      test_db:
        condition: service_healthy
    command: ["python", "-c", "print('Test data loader - customize as needed')"]
    networks:
      - sentinel_test_network
    profiles:
      - fixtures

volumes:
  test_db_data:
    driver: local
  test_reports:
    driver: local
  frontend_test_reports:
    driver: local
  e2e_test_reports:
    driver: local

networks:
  sentinel_test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
